#!/bin/bash

declare -a finalargs
finalargs=()

for o in "$@"; do
    if [ "$o" = "-lc" ]; then
        finalargs+=("/usr/lib/libc.so")
        continue
    fi

    finalargs+=("$o")
done

if [ "$(arch)" = "x86_64" ]; then
    MARCH="-march=x86_64"
elif [ "$(arch)" = "aarch64" ]; then
    # MARCH="-march=armv8-a"
    MARCH=""
else
    MARCH=""
fi

exec /opt/gcc/mold/usr/bin/mold "${finalargs[@]}"
