name: mission-center
base: core20
version: '0.6.2'
adopt-info: mission-center
grade: stable
confinement: strict

plugs:
  system-desktop-files:
    interface: system-files
    read:
      - /var/lib/snapd/hostfs/usr/share/applications
      - /var/lib/snapd/hostfs/usr/share/icons
      - /var/lib/snapd/hostfs/var/lib/flatpak
      - /var/lib/snapd/hostfs/var/lib/snapd/desktop
      - /sys/fs/cgroup/user.slice

  user-desktop-files:
    interface: personal-files
    read:
      - $HOME/.local/share/applications
      - $HOME/.local/share/flatpak/exports/share

slots:
  mission-center:
    interface: dbus
    bus: session
    name: io.missioncenter.MissionCenter

  mission-center-gatherer:
    interface: dbus
    bus: session
    name: io.missioncenter.MissionCenter.Gatherer

apps:
  mission-center:
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
      HW_DB_DIR: $SNAP/usr/share/missioncenter/
      MC_RESOURCE_DIR: $SNAP/usr/share/missioncenter/
      XDG_DATA_DIRS: /var/lib/snapd/hostfs/usr/share:/var/lib/snapd/hostfs/var/lib/snapd/desktop:/var/lib/snapd/hostfs/var/lib/flatpak/exports/share:$SNAP_REAL_HOME/.local/share:$SNAP_REAL_HOME/.local/share/flatpak/exports/share:$XDG_DATA_DIRS
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - network-manager
      - network-observe
      - process-control
      - system-observe
    extensions: [ gnome-3-38 ]
    command: usr/bin/missioncenter
    common-id: io.missioncenter.MissionCenter
    desktop: usr/share/applications/io.missioncenter.MissionCenter.desktop

parts:
  mission-center:
    plugin: nil
    source: .
    override-prime: |
      cp -r $SNAPCRAFT_PART_SRC/snap/local/usr        $SNAPCRAFT_PRIME/
      rm -v $SNAPCRAFT_PRIME/usr/bin/{gdk-pixbuf-query-loaders,glib-compile-schemas,gtk-update-icon-cache}
      sed -i 's|Icon=.*|Icon=usr/share/icons/hicolor/scalable/apps/io.missioncenter.MissionCenter.svg|g' $SNAPCRAFT_PRIME/usr/share/applications/io.missioncenter.MissionCenter.desktop
