name: mission-center
base: core24
adopt-info: mission-center
grade: stable
confinement: strict

plugs:
  system-desktop-files:
    interface: system-files
    read:
      - /var/lib/snapd/hostfs/usr/share/applications
      - /var/lib/snapd/hostfs/usr/share/icons
      - /var/lib/snapd/hostfs/var/lib/flatpak
      - /var/lib/snapd/hostfs/var/lib/snapd/desktop
      - /sys/fs/cgroup/user.slice

  user-desktop-files:
    interface: personal-files
    read:
      - $HOME/.local/share/applications
      - $HOME/.local/share/flatpak/exports/share

slots:
  mission-center:
    interface: dbus
    bus: session
    name: io.missioncenter.MissionCenter

  mission-center-gatherer:
    interface: dbus
    bus: session
    name: io.missioncenter.MissionCenter.Gatherer

apps:
  mission-center:
    environment:
      HW_DB_DIR: $SNAP/usr/share/missioncenter/
      XDG_DATA_DIRS: /var/lib/snapd/hostfs/usr/share:/var/lib/snapd/hostfs/var/lib/snapd/desktop:/var/lib/snapd/hostfs/var/lib/flatpak/exports/share:$SNAP_REAL_HOME/.local/share:$SNAP_REAL_HOME/.local/share/flatpak/exports/share:$XDG_DATA_DIRS
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - network-manager
      - network-observe
      - process-control
      - system-observe
    extensions: [ gnome ]
    command: usr/bin/missioncenter
    common-id: io.missioncenter.MissionCenter
    desktop: usr/share/applications/io.missioncenter.MissionCenter.desktop

parts:
  rustup:
    plugin: rust
    source: .
    rust-channel: "1.80"
    override-build: ""
    override-prime: ""

  mission-center:
    after: [rustup]
    plugin: meson
    source: https://gitlab.com/mission-center-devs/mission-center.git
    source-tag: 'v0.6.0'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/mission-center/current/usr
      - -Dbuildtype=release
      - -Doptimization=2
    organize:
      snap/mission-center/current: .
    parse-info: [usr/share/metainfo/io.missioncenter.MissionCenter.metainfo.xml]
